### ISSUE TITLE
What exact fuzzing techniques have been used?

### ISSUE THREAD

**Issue by JackHFeng** [crytic/echidna#184]
I was looking at codes on how you guys do the fuzzing part. 
Then I found this echidna/lib/Echidna/ABI.hs. Is this the right file where you do the fuzzing of different types of parameters for each function? 
Was there any systematic fuzzing technique used? Like maybe bit flip, byte flip? Some of codes seem to have just random generation and selection, how do you handle duplicate test cases without systematic fuzzing?

**Comment by agroce** [comment]
Jack:  duplicate tests aren't really a problem, with pure random generation, due to the chance of repeating a 256-bit value being essentially zero.  That said, we do some constant mining, and there is a start on a coverage-driven aspect.  But there's no issue with just doing pure random here, in terms of duplicate tests, unless you have a very strange (and easy to fuzz!) contract.
