### ISSUE TITLE
Allow Docker users to specify solidity version

### ISSUE THREAD

**Issue by willclarktech** [crytic/echidna#191]
When I try to run tests on my `pragma solidity ^0.5.2` contract I get the following error:
```
▶ docker run -t -v "$PWD/contracts:/share/contracts" trailofbits/echidna echidna-test /share/contracts/MyContract.sol
/share/contracts/MyContract.sol:13:17: Error: Expected identifier but got 'payable'
        address payable sender;
```
It looks like you've got some support for v0.5.x but the Dockerfile only provides v0.4.25. It would be great if the test tool (and running it via Docker specifically) would allow you to specify the solidity version you want to use and/or automatically respect the `pragma` statement.

**Comment by ESultanik** [comment]
It is using a slightly out-of-date version of Echidna (due to dependency issues with other tools in the container, which will be fixed soon), but you can also try using the Ethereum Security Toolbox Docker container:

https://github.com/trailofbits/eth-security-toolbox

It comes preinstalled with a bunch of different versions of Solidity.

In the long run, we should probably have the Echidna Docker container extend from [`trailofbits/solc-select`](https://github.com/crytic/solc-select).

**Comment by willclarktech** [comment]
Thanks, I actually stumbled on this a short while after posting the issue. It's a nice tool, but a 14GB docker image (`eth-security-toolbox`) is quite a lot to ask of my colleagues...

**Comment by itirabasso** [comment]
You can manually install a specific solc version on your container
```
apt-get install curl
curl -o /usr/bin/solc -fL https://github.com/ethereum/solidity/releases/download/v0.5.2/solc-static-linux
chmod u+x /usr/bin/solc
solc --version
```

**Comment by ggrieco-tob** [comment]
The size of `eth-security-toolbox`  was reduced. It should be usable now.
