### ISSUE TITLE
Echidna fails to run if precompiled contracts are executed in a contract

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#195]
```
contract C {
  function echidna_true() public returns (bool) {
    return true;
  }

  function f() public {
    ecrecover(0,0,0,0);
  }
}
```

```
$ echidna-test precompiled.sol
...
echidna-test: VM failed for unhandled reason, PrecompiledContractError 1. This shouldn't happen. Please file a ticket with this error message and steps to reproduce!
```

**Comment by ggrieco-tob** [comment]
This is an issue in [hevm](https://github.com/dapphub/dapptools/issues/1). A possible workaround is to reimplement the precompiled contracts in Solidity for each test case. I will investigate if this is feasible.

**Comment by ESultanik** [comment]
Is this really an issue with precompiled contracts, or is it just related to any use of the `ecrecover` function?

**Comment by ggrieco-tob** [comment]
Any precompiled contract will trigger this issue. For instance: `identity` will also fail.

**Comment by livnev** [comment]
@ggrieco-tob It's unfortunate that your `ECRECOVER` example fails, since this is the one precompile that `hevm` tries to support so far, since https://github.com/dapphub/dapptools/commit/c4822ce84f5bb4b680371a881de0afe9c7bae8f0

The error message you have is actually not the same as if you'd called one of the other precompiles, which simply aren't implemented. Instead, what you are hitting is incorrect error handling for the precompile in `hevm`: in the case of invalid data the expected behaviour would be to push `0` onto the stack, which would lead solidity to a revert. If you had given it non-exceptional input data then it would actually have worked. I'll look at resolving this soon.

I'm also thinking about actually implementing at least some of the missing precompiles (starting with the elliptic curve operations at 6, 7, 8), in the next few weeks.

**Comment by ggrieco-tob** [comment]
Thanks for fixing the issue in hevm, @livnev ! We will wait until the release in stack of hevm to test it. Do you know when it can be?

**Comment by ggrieco-tob** [comment]
This works in #209. @ESultanik can you please re-test to confirm this?

**Comment by ggrieco-tob** [comment]
This should be fixed.
