### ISSUE TITLE
Echidna crashes when trying to call an nonexistent contract in the constructor

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#296]
Echidna crashes when it tries to run this:

```solidity
contract C {
    constructor() public {
      C c = C(0x1);
      c.f();
    }

    function f() public {}
    
    function echidna_prop() public returns (bool) {
      return true;
    }
}
```

with this error:

```
Analyzing contract: bug.sol:C
echidna-test: Call target doesn't exist
CallStack (from HasCallStack):
  error, called at src/EVM.hs:1465:9 in hevm-0.31-60dymAbvUvX7gSpGnTMjZd:EVM
```

It should catch the nonexistent contract error during the constructor as well.

**Comment by arcz** [comment]
I've been looking a bit into this crash and it is coming from the `hevm` library:
https://github.com/dapphub/dapptools/blob/5c9acddd6bde407db20a5125de270d38a9ee86d5/src/hevm/src/EVM.hs#L1465. I'm wondering why hard crashing `error` is used here instead of the `vmError`.

The `solc` seems to compile the example without complaint, is this a valid contract? I've tried searching but couldn't find any clarification (still new to Solidity).

**Comment by ggrieco-tob** [comment]
Any updates on this @arcz ?

**Comment by ggrieco-tob** [comment]
This is no longer crashing, but the dashboard gets stuck. You can press `escape` and echidna will exit normally (which is good), however, there is no indication that you can do that. Instead, you get a "Starting up, please wait..." message.

**Comment by arcz** [comment]
I think it still crashes, it is now inside the worker thread

**Comment by ggrieco-tob** [comment]
Yeap, I can confirm this, but now it is showing the benchmark mode message (which is expected, since it cannot load any tests)

**Comment by arcz** [comment]
I will work on handling worker exceptions, it's a bit confusing now

**Comment by ggrieco-tob** [comment]
#447 seems to fix this. Please test it.

**Comment by ggrieco-tob** [comment]
Fixed.
