### ISSUE TITLE
Develop "RPC mode" 

### ISSUE THREAD

**Issue by MatthewARinehart** [crytic/echidna#493]
Develop a sort of "RPC mode" where contract code can also be fetched from an "on-chain" source on an as-needed basis, which is sort of what multicontract was designed to do, but on a preload basis

**Comment by SheldonHolmgren** [comment]
This would be a powerful feature and I can't wait to have something like this available in Echidna. This would require fetching not only code but also storage on demand. Hevm supposedly already supports that.

This would make Echidna much easier to use for inspecting contracts that have been already deployed. For example, instead of writing:
```solidity
contract EchidnaTest {
    Market market;
    constructor() {
        market = new Market(some, long, list, of, arguments);
    }
}
```
one could simply do
```solidity
contract EchidnaTest {
    Market market;
    constructor() {
        market = Market(0x66be1bc6C6aF47900BBD4F3711801bE6C2c6CB32);
    }
}
```
The difference would obviously be much more staggering when testing complex systems, which is where echidna is most needed.

There would be several benefits when testing already deployed contracts:
* Easier set up and lower barrier to entry
* More realistic tests
* Lower risk of missing bugs (i.e., echidna failing to find some bugs that manifest only in the particular configuration that is deployed but not in the simple configurations that the user tests with).

**Comment by arcz** [comment]
Done in https://github.com/crytic/echidna/pull/927.
