### ISSUE TITLE
How to call functions with specific arguments?

### ISSUE THREAD

**Issue by PaulRBerg** [crytic/echidna#529]
## Description

I went through the [Echidna tutorial][1] but it didn't account for my use case.

Suppose that you have two functions:

```solidity
function foo(address addr) external {}

function bar(address addr) external {}
```

I'd like to make Echidna call both functions with the same `addr` argument, so that later I can write a property that checks the value of an entry in a mapping:

```solidity
function echidna_test_mapping() external view returns (bool) {
  // Same `addr` as in the function above
  return structs[addr].someValue >= someLowerBound && structs[addr].someValue <= someUpperBound;
}
```

Should I do this by seeding a [corpus][2]? Or will Echidna figure out that it has to call `foo` and `bar`, in this order, with the same `addr`? Or is it that I have a poor understanding of fuzzers and this is not they are supposed to be used?

## Source Code

You can take a look at the `bonds` struct and the `listBond` and `setCollateralizationRatio` functions in `Fintroller.sol`:

https://github.com/MainframeHQ/mainframe-lending-protocol/blob/828bce3abb1d6d81003c166cdd80c354cde8a7f6/contracts/Fintroller.sol

I'd like to check that `bonds[yTokenAddress].collateralizationRatio` is always within some bounds.

[1]: https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna#installation
[2]: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/collecting-a-corpus.md

**Comment by ggrieco-tob** [comment]
> Should I do this by seeding a corpus? Or will Echidna figure out that it has to call foo and bar, in this order, with the same addr? Or is it that I have a poor understanding of fuzzers and this is now they are supposed to be used?

If you let echidna, it will probably call these two functions with the same address. However, the most efficient way to do it is to add one new function:

```solidity
function call_foo_bar_addr() external {
  foo(addr);
  bar(addr);
}
```

You can do this when you are absolutely sure foo and bar should be called with the same address, and it is useless to do something else.

**Comment by PaulRBerg** [comment]
> If you let echidna, it will probably call these two functions with the same address.

Hmm, I'm not sure about that. Here's a [corpus][1] that Echidna generated for me. It called `listBond` with 0x0000000000000000000000000000000000090000 and `setCollateralizationRatio` with 4b8321cc14d6543d476f8f4a80bf331140e95e94.

> You can do this when you are absolutely sure foo and bar should be called with the same address, and it is useless to do something else

Yeah that's precisely what I want to do.

> Btw, I tend to use msg.sender to avoid hardcoded addresses but you can use a fixed one if you want.

I can see why `msg.sender` works in many cases, but not for me. This is actually another question - if `addr` must be a contract, should I create a mock version of it with just the functions triggered by my Echidna property?

See `yToken.isYToken();` in the [listBond function][2];

[1]: https://gist.github.com/PaulRBerg/92f572a94033da2544a3b279f53c6482
[2]: https://github.com/MainframeHQ/mainframe-lending-protocol/blob/828bce3abb1d6d81003c166cdd80c354cde8a7f6/contracts/Fintroller.sol#L167-L182

**Comment by PaulRBerg** [comment]
After mulling over this issue, I think I shouldn't test my scenario with a property. As it says in [When and how use assertions][1]:

> On the contrary, using an explicit echidna property will randomly execute transactions and there is no easy way to enforce exactly when it will be checked.

It looks like I should test this via assertions. However, if I am to follow [John Regehr's recommendations][2] (as you suggest), I shouldn't have an assertion at all, since `collateralizationRatio` can never be smaller than the lower bound and bigger than the upper bound:

```solidity
function setCollateralizationRatio(YTokenInterface yToken, uint256 newCollateralizationRatioMantissa) {
    ...
    require(
        newCollateralizationRatioMantissa <= collateralizationRatioUpperBoundMantissa,
        "ERR_SET_COLLATERALIZATION_RATIO_UPPER_BOUND"
    );
    require(
        newCollateralizationRatioMantissa >= collateralizationRatioLowerBoundMantissa,
        "ERR_SET_COLLATERALIZATION_RATIO_LOWER_BOUND"
    );
    ...
```

[1]: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/assertion-checking.md
[2]: https://blog.regehr.org/archives/1091

**Comment by ggrieco-tob** [comment]
> Hmm, I'm not sure about that. Here's a corpus that Echidna generated for me. It called listBond with 0x0000000000000000000000000000000000090000 and setCollateralizationRatio with 0x4b8321cc14d6543d476f8f4a80bf331140e95e94.

It will eventually. You can check this example:

```solidity
contract C {

  address internal fa;
  address internal ba;

  function foo(address addr) external {
    fa = addr;
  }

  function bar(address addr) external {
    ba = addr;

  }

  function echidna_foo_bar() public returns (bool) {
    return (fa == address(0) || ba == address(0) || fa != ba);
  }

}
```

Echidna will break the property in seconds:

```
Analyzing contract: foo_bar.sol:C
echidna_foo_bar: failed!💥  
  Call sequence:
    bar(0xdeadbeef)
    foo(0xdeadbeef)


Seed: 5050661239606874044
```

>  if addr must be a contract, should I create a mock version of it with just the functions triggered by my Echidna property?

Yes.

**Comment by ggrieco-tob** [comment]
>  I shouldn't have an assertion at all, since collateralizationRatio can never be smaller than the lower bound and bigger than the upper bound:

If you are completely sure that the implementation always enforces this property, then there is no point of using testing at all. Otherwise, perhaps you should try.

**Comment by PaulRBerg** [comment]
> It will eventually. You can check this example:

"Eventually" is a key word for noobs like me! Thanks so much for your help.

> If you are completely sure that the implementation always enforces this property, then there is no point of using testing at all. Otherwise, perhaps you should try.

I see. Knowing what to test is a skill in and of itself.

I'll close this issue since the original concern has been addressed.

**Comment by CodeGodz** [comment]
Hey @ggrieco-tob, I'm also having a look at this and in our case of scam contracts we only know that a function is very likely to be called with the devs address (when having an address argument), however we are not sure which one. I could parse the solidity file with slither, check the arguments, if there is an address argument write a new function below (and perhaps blacklisting the original)

```
func(arg1, arg2) {
    original_func(0x...., arg1, arg2);
}
```
However, this seems very cumbersome, especially since we of course can have multiple variants (e.g. two address arguments that I have to alternate). I could let it run completely and then parse the corpus and replace addresses, and rerun it, but also that seems a bit of a stretch.

Any other way of "forcing" Echidna to use a specific address as function argument? Alternatively, wouldn't it be nice to be able to set all seeds restrictions in a config like we do with `sender`. Such that for each ABI type we can seed echidna like:

```
address: [0xx, 0x...],
int8: [10, 11, 2],
...
```

Wish I could help instead of asking you all the time.... but I cannot code Haskell, as far as I can see I could imagine this being randomly sampling from a user provided yaml (in the form of a hashmap) in `ABI.hs` rather than randomly generating input

**Comment by ggrieco-tob** [comment]
@CodeGodz if you know there is an address to be used in some argument, but you don't know which one, you have two options:

1. Add the developer address into the `sender` field: this will cause echidna to use that address as the origin for the transactions but also to add into the internal dictionary to use it in any function that takes address as inputs. 
2. Add a new public field initialized as the developer address. This will cause echidna to add it into the dictionary, but without changing the `sender`.

Clearly, (1) is useful if you want to test the developer account impersonation (where msg.sender == 0x...), and (2) is if you want to avoid such case.

**Comment by CodeGodz** [comment]
@ggrieco-tob hey, took me a bit of time to carefully check, I tried both options before, and while it indeed somtimes finds the call sequence to execute the mint (50K tests), it does seem to call the mint function with a strong preference for addresses that are _not_ the dev or hardcoded (**see results at the bottom**)

I used this contract ([pastebin](https://pastebin.com/XnA4eesc)) and the following config:
```yaml
prefix: crytic_
deployer: "0xA143E75f896134a8B1f9153c71728A0289670e90"
sender: ["0xA143E75f896134a8B1f9153c71728A0289670e90"]
psender: "0xA143E75f896134a8B1f9153c71728A0289670e90"
testLimit: 50000
maxTimeDelay: 0
maxBlockDelay: 0
corpusDir: "add_check/corpus"
```
For this specific contract, `mintToken` will mint tokens (suprising right haha) to the provided wallet when called by the owner (`0xA143E75f896134a8B1f9153c71728A0289670e90` here). Based on the config, and `0xA143E75f896134a8B1f9153c71728A0289670e90` being hardcoded in the contract as `projectAddress` I would expect this address to be used  predominately, like you described. 

To look at this I used the Python script below. Basically just running echidna 5 times and parsing the used arguments from the corpus files. Then coutning how often addresses where used as argument for the call. 

```python
import os
import csv
from glob import glob
from collections import Counter
import shutil

sol_file = 'test.sol'
contract_name = 'TrafficBeans'
config_file = 'echidna.yaml'
corpus_dir = 'add_check/corpus' # Should match that in the config
output_file = 'add_count.txt'
runs = 5

with open(output_file, 'w') as out:
    writer = csv.DictWriter(out, delimiter = '\t', fieldnames = ['run', 'address', 'count'])
    
    for run_id in range(runs):
        print('RUN: {}'.format(run_id))
        
        # Clear corpus directory if exists, bit saver to use shutil with a 
        # directory path rather than a rm -rf * in a folder
        shutil.rmtree(corpus_dir, ignore_errors=True)
        os.mkdir(corpus_dir)
        
        # run Echidna
        cmd = 'echidna-test {} --config {} --contract {}'.format(sol_file, config_file, contract_name)
        print(os.popen(cmd).read())
    
        # Get the coverage files
        coverage_files = [file for file in glob(corpus_dir +'/coverage/*.txt')]

        # Store how often an address was used to call the mint
        call_count = Counter()

        for file in coverage_files:
            with open(file,'r') as in_file:
                data = json.loads(in_file.read()) # not sure why json.load didnt work
                for tx in data:
                    call = tx['_call']                
                    # Function data
                    func_name = call['contents'][0]
                    # Check if this is the scam function
                    if func_name == 'mintToken':
                        func_args = call['contents'][1]
                        arg_add = func_args[0]['contents']
                        call_count[arg_add] +=1

        # Write data to the tsv
        data = [{'run': run_id, 'address': add, 'count': count} for add, count in call_count.items()]
        writer.writerows(data)

```

Then we visualize the the TSV:
![image](https://user-images.githubusercontent.com/92177790/160427987-b3c1115a-322e-4c25-abaa-855d56e713e8.png)
From the density distribution in (**A**) we see some peaks (with high counts - x-axis) far outside the distribution, when looking at them (**B**) these do not appear to be the dev address.

Probably easier to look at all this on **[this google colab](https://colab.research.google.com/drive/1IrvdD6qfpPYlA2rz-Hh8SxDPxjlv-Xlj?usp=sharing)** - used 5k instead of 50K here.

**Comment by ggrieco-tob** [comment]
This looks very interesting. Can you please rerun your experiments using different `freqDict` value in your config file (which is a float from 0.1 to 0.9), which specifies how often our tool uses the dictionary of values? Also, if you want to run echidna from python, try this code: https://github.com/crytic/echidna-parade/blob/main/echidna_parade/echidna.py

**Comment by ggrieco-tob** [comment]
The corpus that you analyze only contains sequences of transactions that produce different coverage (accumulated over time), so it is very noisy. This means that if the `dev` address allows to explore a couple more of line of code, then it will be slightly more used. IMHO, you need to measure if you manage to reach or not a line that depends on the usage of `dev` instead.

**Comment by CodeGodz** [comment]
Aah I see, when I on purpose increase the frequency of the dev address by hardcoding it four times as address (`add1`, `add2`, etc.) and then use `0.9` it indeed does fail all tests yet not showing up as top address in the previous figures - in line with what you say

**Comment by ggrieco-tob** [comment]
This is a very interesting project indeed and your plots are nice. Is there any public repository where we can follow your experiments? (otherwise, feel free to show your progress in EmpireHacking)
