### ISSUE TITLE
Check for revert in the latest transaction and skip test

### ISSUE THREAD

**Issue by ggrieco-tob** [crytic/echidna#583]
If the latest executed transaction is reverted, there is no point in executing the test function. There will no change in the contract state. We should skip that test, and generate another transaction,

**Comment by agroce** [comment]
Ran some benchmarks of master vs. dev-opt-asserts, and while I don't have any code that I think is likely reverting a lot, so really a good benchmark, just code that pushes/pops to an array I see about a 5% improvement in test throughput, which is good since I'd imagine this is close to a lower bound on speedup

**Comment by ggrieco-tob** [comment]
Fixed. Thanks for the benchmarking.
