### ISSUE TITLE
Multi-contract example breaks since version 1.6.1

### ISSUE THREAD

**Issue by jyao15** [crytic/echidna#676]
The basic multicontract example (https://github.com/crytic/echidna/tree/master/examples/solidity/basic_multicontract) works well from version Echidna 1.3.0.0 to 1.6.0, but fails from version 1.6.1 to 1.7.1. Echidna mistakenly passes the check. By inspecting the coverage file, I find the test function in Bar contract is never called. I am using precompiled binaries on Ubuntu.

**Comment by ggrieco-tob** [comment]
The multicontract example still works, but it cannot be used directly from the examples folder there. The initialization should be re-created, otherwise, the hashes used to determinate which contract is executed, will change. That is why it is disabled in the CI tests:

https://github.com/crytic/echidna/blob/4aeffd4baac7a3f01ec2185528a5b21156204683/src/test/Tests/Integration.hs#L121-L127

You can find a tutorial on how to do it here: https://github.com/crytic/building-secure-contracts/blob/master/program-analysis/echidna/end-to-end-testing.md#end-to-end-testing-with-echidna-part-i
