### ISSUE TITLE
Seeds aren't the same accross platforms

### ISSUE THREAD

**Issue by Arinerron** [crytic/echidna#762]
Hi,

I'm on Arch Linux on an i7-9750H and my friend is on macOS on the Mac M1. We both tried running echidna against the same target contract with the same config and got entirely different results. I can't share the contract sadly but I thought I'd mention this here.

-Aaron

**Comment by ggrieco-tob** [comment]
If your contract deploys other contracts, the resulting address could change from one machine to another, even if you use the same platform. The reason is because Solidity includes a hash in the metadata of the contract (deployed on chain), and this hash depends on the path where the contracts are located. I think the best we can do is to try to document this limitations.

**Comment by Arinerron** [comment]
Ah that makes a lot of sense. Thanks!
