### ISSUE TITLE
Assertion mode in 0.8.x - unexpected behavior

### ISSUE THREAD

**Issue by elizabethdinella** [crytic/echidna#809]
Hello, I am running Echidna on a toy contract, and am seeing some unexpected behavior. 

According to #716  I would expect echidna running in `--test-mode assertion` to report an overflow when fuzzing the following contract (with solidity version 0.8.x). However, it did report any failures. 

```
contract HelloWorld {

   event AssertionFailed();
   constructor() { }

   function check(string memory newMessage) public {
      uint8 baz = 255;
      uint8 bar = 7;
      uint8 foo = baz + bar;
      if (!(foo >= baz && foo >= bar)) {
            assert(false);
            emit AssertionFailed();
      }
   }
}
```

I ran echidna on the above contract in various settings and found the following results: 

With solc version 0.8.5, 
Echidna in `–test-mode assertion` does not report any failure - (NOT EXPECTED / BUG) 
Echidna in `–test-mode overflow` reports an overflow (EXPECTED)

With solc version 0.4.26, 
Echidna in `–test-mode assertion` reports the assertion failure but no overflow (EXPECTED)
Echidna in `–test-mode overflow` does not report anything (EXPECTED) 

With solc version 0.8.x and `test-mode assertion` I would expect echidna to report an overflow, or at least an assertion failure.

**Comment by Jaime-Iglesias** [comment]
Hey @elizabethdinella 

Because of Solidity's 0.8 native overflow protection your statement `assert(false)` is not reachable in `--test-mode assertion`, because your function will revert before that code is reached.

I would speculate that, `--test-mode overflow` is able to catch that revert and notify you about it.

I defer to Echidna master @ggrieco-tob for the proper explanations w.r.t to my statements above and how Echidna treats the overflow mode.

If you want to use `--test-mode assertion` and catch the overflow (or other reverts) you can do something like the following:

```solidity
// SPDX-License-Identifier: Apache-2.0.
pragma solidity =0.8.5;
contract HelloWorld {

   event AssertionFailed();
   constructor() { }

    function check() public {
        try this.oh_no_overflow() returns (uint8) {
            assert(false);
        } catch (bytes memory) {
            assert(true);
            emit AssertionFailed();
        }
    }

    function oh_no_overflow() public pure returns (uint8) {
        uint8 baz = 255;
        uint8 bar = 7;
        uint8 foo = baz + bar;

        return foo;
    }
}
```
In this particular case, because `oh_no_overflow()` is a public function when we use `this.oh_no_overflow()` we are forcing an external call to ourselves that we can then try/catch (internal calls cannot be tried/catched)

Here are the results of running the above snippet with `--test-mode assertion`
<img width="855" alt="image" src="https://user-images.githubusercontent.com/22358726/181938704-51d63173-bcb1-4942-8883-c30596ed42b9.png">

Alternatively (and this is the approach that I would recommend) you could wrap your contract with another contract and try/catch the function calls to make sure you are achieving your desired results, something like this:

```solidity
// SPDX-License-Identifier: Apache-2.0.
pragma solidity =0.8.5;

contract HelloWorld {
    function oh_no_overflow() public pure returns (uint8) {
        uint8 baz = 255;
        uint8 bar = 7;
        uint8 foo = baz + bar;

        return foo;
    }
}

contract Wrapper {
    HelloWorld private _myContract;

   event AssertionFailed();
    constructor() { 
        // We instantiate the contract we want to test
        _myContract = new HelloWorld();
    }

    function check() public {
        // We make a call to the contract we want to test and try/catch it
        try _myContract.oh_no_overflow() returns (uint8) {
            assert(false);
        } catch (bytes memory) {
            assert(true);
            emit AssertionFailed();
        }
    }
}
```

This is the result of running the Wrapper version
<img width="855" alt="image" src="https://user-images.githubusercontent.com/22358726/181939312-1fccd8cf-9963-4034-b591-ba50a30ba56b.png">

Hope that helps.

**Comment by elizabethdinella** [comment]
Thank you very much, this provided much clarity!
