### ISSUE TITLE
Document 1-line installers

### ISSUE THREAD

**Issue by montyly** [crytic/echidna#817]
We should document in Echidna's readme
https://www.npmjs.com/package/@crytic/echidna

We can also move it to `@trailofbits/echidna` I think. cc @bohendo 

Related https://github.com/crytic/echidna/issues/811

**Comment by montyly** [comment]
Additionally `brew install echidna` (cc @elopez)

**Comment by bohendo** [comment]
The echidna npm package was an experiment that, in my opinion, should be discontinued rather than ported over to the more official `@trailofbits` scope & publicized. My grand vision for this suite of npm packages ended up being somewhat misguided: we can't provide much more than just echidna, and even this isn't really a "1-line" installation as it doesn't help the user install dependencies such as slither, solc-select, etc.

`brew install echidna` is better, this should be the solution we point mac users to until we have a more platform-agnostic installation process a la #811
