### ISSUE TITLE
Option to force echidna to use ONLY the addresses in the `sender` list

### ISSUE THREAD

**Issue by rappie** [crytic/echidna#834]
Not sure if this is currently a bug or a feature.

Echidna seems to use any address it can find in the code and the etheno log file as `from` address for transactions. In my day-to-day use this is often not what I want. I'd like to have full control over the `from` addresses both to reduce the search space and to force certain scenarios.

Example:
When fuzzing ERC-20 tokens I have a `victim` user whose balance and allowances should only increase. I have deliberatly left the address of this user out of the `sender` list. However, the address is in the code (to check the balance) and in the etheno log. Echidna can (and will) use this address to do a simple `transfer(0x123, 1)` and break the invariant.

Suggestion:
- Add an option in the echidna settings file to force using only the addresses in the `sender` list.
- To me personally it would make more sense to make this the default and perhaps have a "search for more senders in the code" setting

**Comment by ggrieco-tob** [comment]
I don't think we will implement this, but echidna is no longer calling arbitrary address, but a small number of them (e.g. 0x1fffff). If a new contract is created, it will be added into the dictionary, but it should be still manageable. This is very useful when using RPC since will minimize the number of slots fetched.
