### ISSUE TITLE
How to build echinda-test

### ISSUE THREAD

**Issue by nickdammy** [crytic/echidna#842]
Hi, 

How can I build and edit this project on my local machine? I have pulled the latest version and I would like to build it and make changes to it (locally). The docker container already has the pre-compiled echinda-test file. How do I re-generate this?

**Comment by elopez** [comment]
Hi, you can build Echidna with Stack ([instructions here](https://github.com/crytic/echidna#building-using-stack)) or using Nix ([see here for instructions](https://github.com/crytic/echidna#building-using-nix-works-natively-on-apple-m1-systems))

**Comment by nickdammy** [comment]
I spawned an Ubuntu terminal. I have loaded stacks, echidna, and "solc", and I am able to run the contracts in the test/solidity folder. I am new to Echidna, could you please explain how I can make changes to the source code(locally), build, test, and see those changes?

**Comment by elopez** [comment]
Just to confirm, are you trying to modify Echidna, the fuzzing tool itself? or do you want to try running Echidna with different solidity contracts and change solidity code?

if it's the tool itself that you want to modify, you can follow the instructions I linked on my previous comment. You will need to get familiar with the Haskell language (the language used to create Echidna), and Stack or Nix.

If you just want to learn how to use Echidna, take a look at the tutorials in the building secure contracts repo: https://github.com/crytic/building-secure-contracts/tree/master/program-analysis/echidna

**Comment by nickdammy** [comment]
hi elopez, it is the tool I would like to modify. 

Here is what I have so far
<img width="523" alt="image" src="https://user-images.githubusercontent.com/105457895/199151697-d66800bb-64dc-43c3-9bd0-de139de570b0.png">

From what I understand, the next step is "stack install echidna-test, " which gives an error message. Could you please list and explain the next steps from here? Could you also provide a screenshot building echidna?

**Comment by elopez** [comment]
If you want to build echidna with stack, first you'll need to install the dependencies in your system (libreadline, libsecp256k1, libff). If you're on Ubuntu, libreadline is available as the `libreadline-dev` package. For the other two, you can read the scripts we use in CI to build them for instructions: [secp256k1](https://github.com/crytic/echidna/blob/master/.github/scripts/install-libsecp256k1.sh) and [libff](https://github.com/crytic/echidna/blob/master/.github/scripts/install-libff.sh)

Then you'll need a copy of the echidna git repository (`git clone https://github.com/crytic/echidna`); move into it (`cd echidna`) and run stack (`stack build` and then `stack install`). Depending on where you installed the dependencies, you may need to add `--extra-include-dirs=/foo/bar` and `--extra-lib-dirs=/foo/bar` arguments so that stack can find the dependencies. You can refer to the [Stack user guide](https://docs.haskellstack.org/en/stable/GUIDE/) and the [build command page](https://docs.haskellstack.org/en/stable/build_command/) for more details on how to use Stack.

If you have any concrete errors while building Echidna you can ask here or [reach out on Slack](https://github.com/crytic/echidna#getting-help)

**Comment by ggrieco-tob** [comment]
It seems we already have instructions, please reopen if necessary.
