### ISSUE TITLE
Build a docker image to run echidna inside it

### ISSUE THREAD

**Issue by bogdynator** [crytic/echidna#875]
Hello, I am having an issue when I am trying to build a docker image from trailofbits/eth-security-toolbox and run echidna-test on my contract

This is an example:

```
FROM trailofbits/eth-security-toolbox

COPY . project

WORKDIR project

RUN ls

RUN ls ./contracts

RUN solc-select install 0.8.15
RUN solc-select use 0.8.15

RUN solc --version

CMD ["echidna-test" ,"./contracts/StakingTest.sol", "--contract", "StakingTest", "--config", "echidna-config.yaml"]
```

when I try to run it, I get the following error:
`
/usr/local/bin/echidna-test: /usr/local/bin/echidna-test: cannot execute binary file
`

I checked if the contracts are copied in the image with those ls commands and they are.

**Comment by elopez** [comment]
Hi! This happens because the entrypoint defined in the eth-security-toolbox image is "bash", so by defining `CMD` on your dockerfile, the container ends up executing "bash /usr/local/bin/echidna-test ...", which is not what you want. You can fix it by overriding the entrypoint by adding `ENTRYPOINT []` to your Dockerfile.

As a sidenote, I'd recommend using the echidna docker images we provide in [`trailofbits/echidna`](https://hub.docker.com/r/trailofbits/echidna) and [here on GHCR](https://github.com/crytic/echidna/pkgs/container/echidna%2Fechidna) instead of eth-security-toolbox. They are lighter and get automatically built on new echidna releases.

**Comment by bogdynator** [comment]
thanks, I replaced the image with trailofbits/echidna and do what you said, and now it works
