### ISSUE TITLE
For some reason my echidna test isn't running

### ISSUE THREAD

**Issue by mattjaf** [crytic/echidna#881]
![image](https://user-images.githubusercontent.com/5776918/209523929-25196dbd-7f54-486f-8073-0eace57bf1d4.png)
```sh
ethsec@2ff6fa4f1a2c:~$ echidna-test /src/contracts/test/fuzzing/LibraryFuzzTest.sol --contract LibraryFuzzTest --config /src/contracts/test/fuzzing/config.yaml
echidna-test: /src/contracts/test/fuzzing/config.yaml: openBinaryFile: does not exist (No such file or directory)
```

Oh, btw I started it with the script:
```json
"toolbox": "docker run -it --rm -v PWD:/src trailofbits/eth-security-toolbox"
```
------

I tried to add a $ sign in front of the PWD and its throwing:
```sh
docker: Error response from daemon: create $PWD: "$PWD" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
error Command failed with exit code 125.
```

maybe that's my issue?

Err, I'm on windows, I switched it to: 
```sh
"toolbox": "docker run -it --rm -v %cd%:/src trailofbits/eth-security-toolbox"
```
and tried to run it again, now its throwing:
```
ethsec@8004a1cef0c8:~$ echidna-test /src/contracts/test/fuzzing/LibraryFuzzTest.sol --contract LibraryFuzzTest --config /src/contracts/test/fuzzing/config.yaml
echidna-test: Couldn't compile given file
stdout:
stderr:
ERROR:CryticCompile:Invalid solc compilation "//" is not a valid file.
```
Oh that error was from a bad comment in my config file

-----

err, it might be tripping about my contract imports being outside the directory I'm pointing to?

maybe not?

anyways now its throwing:
```sh
ethsec@4622870de62f:~$ echidna-test /src/contracts/test/fuzzing/LibraryFuzzTest.sol --contract LibraryFuzzTest --config /src/contracts/test/fuzzing/config.yaml
Analyzing contract: /src/contracts/test/fuzzing/LibraryFuzzTest.sol:LibraryFuzzTest
echidna-test: Test "echidna_test_find_discrepancy" has arguments, aborting
```
which seems to be an issue with my test itself, hmmmmmm....

Please help,

Thank you in advance and merry Christmas

**Comment by 0xPhaze** [comment]
mentioned here #869 (@ggrieco-tob perhaps this should get more attention as I believe this to be very unintuitive and limiting).

functions with the signature `echidna_*() returns (bool)` should not contain any arguments (they cannot be fuzzed for some reason). It's briefly described [here](https://github.com/crytic/echidna#writing-invariants). 
Instead, you'll want to run the campaign via [assertion mode](https://github.com/crytic/echidna/wiki/Config), i.e. add `--test-mode assertion`:
- change the function to any regular function (not using "echidna_" and `returns (bool)`)
- change the `return` to an `assert()`.

We should probably update the docs, because I couldn't find this explained anywhere nicely in the readme and this is most likely the default desired behaviour of echidna.

**Comment by ggrieco-tob** [comment]
@elopez can you check if docker is working as expected here?

**Comment by elopez** [comment]
@ggrieco-tob: Judging by the latter edits it seems to be working fine 👍 The last error message very much sounds like the problem @0xPhaze described (property with an argument), which means compilation & config parsing succeeded.

**Comment by ggrieco-tob** [comment]
Great. Let's close this.

**Comment by mattjaf** [comment]
Yes, its working thank you guys!
