### ISSUE TITLE
Bus error: 10 and segmentation fault when running echidna-test 

### ISSUE THREAD

**Issue by Yingtong-Liu** [crytic/echidna#899]
**zsh: segmentation fault  echidna-test agent.sol --contract Agent**

I am testing a contract already deployed in my local network. The agent.sol calls the functions in the target contract. Weirdly, echidna couldn't go very far (less than a minute) and constantly reporting either "segmentation fault"  or "Bus error: 10" and then simply stops. The contract I am testing is quite complex and its public function parameters are all very large values. 

It's very hard to know what really happened with such errors reported from echidna, any suggestions on debugging and guesses on what might go wrong? Thanks.

**Comment by ggrieco-tob** [comment]
@elopez can you help debugging here please? :slightly_smiling_face:

**Comment by elopez** [comment]
This looks like a native code crash, which is not common for Haskell programs. Can you share more info about your setup and the issue? Things like:

* hardware you are using, hardware architecture (x86_64/ARM), OS, OS version
* echidna version, and how you got it installed
* does this happen only on the graphical mode or also if you use the `--format text` option?
* is your computer working fine otherwise, or are you seeing other crashes lately? (there's a slim chance that issues like these could be caused by a hardware issue)
* if you can share the project you're fuzzing to try and reproduce the issue on our side, that would be great too.

**Comment by Yingtong-Liu** [comment]
@elopez Thanks for the reply.

1. I am using a MacOS, Version 13.1, ARM.
2. Echidna 2.0.4, installed by running "brew install echidna"
3. Both
4. Yes, it works fine while testing another relatively simple project (easy ERC20 contracts)
5. I am sorry that it's very hard to share the whole project. There are quite a lot of dependent contracts that I deployed into my local network since echidna now can't support mainnet network forking. What I can share is the [agent.sol](https://github.com/Yingtong-Liu/echidna_debugging/blob/main/agent.sol), though you can't run it. There are some hardcoded contract addresses that only existed in my local network in the agent.sol.

**Comment by Yingtong-Liu** [comment]
I am closing this issue since it turned out to be a hardware or MacOS version problem. Tested it on a Ubuntu22.04 VM and it has no problems.
